### ISSUE TITLE
`The 'cache' field on 'RequestInitializerDict' is not implemented` on Cloudflare next-on-pages

### ISSUE THREAD

**Issue by Enalmada** [apollographql/apollo-client-nextjs#102]
I tried my next.js apollo client app out on [next-on-pages](https://github.com/cloudflare/next-on-pages) and got the following error (including the ... truncation):
```
ApolloError: The 'cache' field on 'RequestInitializerDict' is not implemented.
    at new i (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:208:157)
    at file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:208:38036
    at x (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:212:48386)
    at file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:212:48312
    at new Promise (<anonymous>)
    at Object.then (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:212:48279)
    at Object.error (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:212:48396)
    at T (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:399:1919)
    at P (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:399:2282)
    at N.error (file:///tmp/tmp-24966-eRtM9XM1mEDn/__next-on-pages-dist__/functions/[locale]/app/task/[id].func.js:399:2844) {
  name: ApolloError,
  graphQLErrors: Array(0),
  protocolErrors: Array(0),
  clientErrors: Array(0),
  networkError: Error: The 'cache' field on 'RequestInitializerDict' is not implemented.
    at globalThis.fetch (f…
  ...
}
```

It seems to be from this `fetchOptions: { cache: "no-store" },`
```
function makeClient() {
  const httpLink = new HttpLink({
    uri: "https://example.com/api/graphql",
    fetchOptions: { cache: "no-store" },
    ...
  });
```
~ https://github.com/apollographql/apollo-client-nextjs#in-ssr

Putting it here for anyone that happens to be trying to use apollo client on next-on-pages and searching for the error.  It took me a while to track down as the error isn't clear. It cuts off before it looks like it might tell you where it is coming from.

**Comment by phryneas** [comment]
Interesting!

`cache: "no-store"` is a Next.js specific cache optimization - I didn't know that there are runtimes not implementing that.

This seems to be a thing specific to `next-on-pages`, which seems to not be mentioned in the [docs](https://nextjs.org/docs/app/building-your-application/caching#data-cache)  for this Next-specific `fetch` option, so I'm not sure if it's a good idea to add that additional complexity to our README or not. But it definitely makes sense to have this issue here as a place for people to come and find it!

Thanks for bringing this to our attention!
