### ISSUE TITLE
Issues with build Invariant Violation

### ISSUE THREAD

**Issue by margaritaav98** [apollographql/apollo-client-nextjs#97]
Hi everyone!

I am implementing the library as the documentation say, I don't have any problems in the bowser, however when I run: yarn build I have this issue and I don't know how I can resolve:

**Issue:**

 info Generating static pages (7/9)Invariant Violation: An error occurred! For more details, see the full error text at https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.3%22%2C%22message%22%3A47%2C%22args%22%3A%5B%5D%7D
    at new InvariantError (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/ts-invariant/lib/invariant.cjs:16:28)
    at Object.invariant (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/ts-invariant/lib/invariant.cjs:28:15)
    at Object.invariant (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/utilities/globals/globals.cjs:56:21)
    at useApolloClient (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/react/hooks/hooks.cjs:34:13)
    at useLazyQuery (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/react/hooks/hooks.cjs:392:42)
    at TestGraphPage (/Users/m2v5p4i4/Desktop/proyectos/jd-front/.next/server/pages/TestGraphPage.js:93:77)
    at Wc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Xc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409) {
  framesToPop: 1
}

Error occurred prerendering page "/TestGraphPage". Read more: https://nextjs.org/docs/messages/prerender-error
Invariant Violation: An error occurred! For more details, see the full error text at https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.3%22%2C%22message%22%3A47%2C%22args%22%3A%5B%5D%7D
    at new InvariantError (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/ts-invariant/lib/invariant.cjs:16:28)
    at Object.invariant (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/ts-invariant/lib/invariant.cjs:28:15)
    at Object.invariant (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/utilities/globals/globals.cjs:56:21)
    at useApolloClient (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/react/hooks/hooks.cjs:34:13)
    at useLazyQuery (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/@apollo/client/react/hooks/hooks.cjs:392:42)
    at TestGraphPage (/Users/m2v5p4i4/Desktop/proyectos/jd-front/.next/server/pages/TestGraphPage.js:93:77)
    at Wc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Xc (/Users/m2v5p4i4/Desktop/proyectos/jd-front/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
- info Generating static pages (9/9)

> Export encountered errors on following paths:
        /TestGraphPage
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is the file where I did the use of uselazyQuery:
'use client';
import { GET_USER_BY_STATUS } from '@/graphql/queries/user';
import { FC, useEffect, useState } from "react";
import { List, ListItemText } from "@mui/material";
import { useLazyQuery } from "@apollo/client";

const TestGraphPage: FC = () => {
  const [lazyDataUser, dataUser] = useLazyQuery(GET_USER_BY_STATUS);
  const [users, setUsers]: Array<any> = useState();
  useEffect(() => {
    lazyDataUser({
      variables: {
        promoterCode: "001", status: "GENERATED"
      },
    });
  }, []);

  useEffect(() => {
    if (dataUser.data) {
      setUsers(dataUser.data.getUserByStatusAndPromoterCode.users)
    }
  }, [dataUser.data]);

  return (
    <div>
      <List component="nav" aria-label="mailbox folders">
        {users?.map((user: any) => (
          <>
            <ListItemText primary={user?.firstName} />
          </>
        ))}
      </List>
    </div>
  );
};

export default TestGraphPage;

**Comment by phryneas** [comment]
I'm sorry, I missed this issue back when you opened it.

Since it's been so long I assume that you find a way around this (most likely, your component was not wrapped in a Provider), and will close the issue.

If the question is still relevant, please feel free to reopen the issue.
